# root
root: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - '@magicdawn'
  - 'plugin:@typescript-eslint/recommended'

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-extra-semi': off
